### ISSUE TITLE
Image processing attributes start as wrong type

### ISSUE THREAD

**Issue by S1MP50N** [Steve-Mcl/node-red-contrib-image-tools#10]
Hi, 

Thanks for the contribution, finding it very useful. This is a minor bug observed that tripped me up for 10 mins. Creating a new image node flow. When selecting an action, such as crop, the properties x,y,w, and h are all set to 'msg.' type. If you do not change these to be 'number' type the flow will silently fail. Observing the logs it became obvious why. 

`(node:25) UnhandledPromiseRejectionWarning: Error: x and y must be numbers
    at Jimp.throwError (/data/node_modules/@jimp/utils/dist/index.js:26:13)
    at Jimp.cropQuiet (/data/node_modules/@jimp/plugin-crop/dist/index.js:29:82)
    at Jimp.(anonymous function) [as crop] (/data/node_modules/@jimp/core/dist/index.js:1222:23)`

It may be worth catching the error and showing it, seeing if you can change the default type to number or changing the info text alongside to say "Must be a number type".

Thanks again

**Comment by Steve-Mcl** [comment]
Hi I would like to box this off, could you reply with a small demo node-red flow that demonstrates this issue please?

**Comment by Steve-Mcl** [comment]
@S1MP50N I think I understand now.

If I drop an image node onto the editor & select `crop` function, the x,y,w,h properties are all set to `msg` and are empty.  I suspect at this point you simply typed a number in rather than passing a msg in?



Unfortunately this is user error (e.g. it is legal in JS to have an object property named "100") ...
![image](https://user-images.githubusercontent.com/44235289/81306150-11a8bb00-9077-11ea-9825-8da37daf8cc3.png)
... and so this situation cannot be avoided.  I _could_ default the inputs to number type but then I'll get questions like "how can i send the x & y values in from another node! - cant win TBH.

I'm going to close this issue.

If you have a better idea, please re-open the issue.
